#!/usr/bin/env bash
# Transfers a file from our client to a server
#
# variables
path=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>$1 && pwd)
filename=$(basename "$BASH_SOURCE")
brown='\033[0;33m'
reset='\033[0m'
file="$1"
ip="$2"
user="ubuntu"
key="~/.ssh/id_rsa"

if [ $# -eq 2 ]; then
    scp -i "$key" -o StrictHostKeyChecking=no "$file" "$user"@"$ip":/home/"$user"/
else
    # Display usage message
    echo -e "Usage: ${brown}./$filename FILENAME IP USERNAME PATH_TO_SSHKEY${reset}"
fi
